/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002201",
        "on-tertiary-fixed-variant": "#444844",
        "primary-fixed": "#bcf0ae",
        "tertiary": "#363a37",
        "on-tertiary-container": "#c0c4bf",
        "background": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#d1ebb5",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d1dbec",
        "inverse-primary": "#a1d494",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface": "#f8f9ff",
        "on-tertiary-fixed": "#191c1a",
        "surface-tint": "#3b6934",
        "outline-variant": "#c2c9bb",
        "on-secondary-fixed-variant": "#384d25",
        "surface-variant": "#d9e3f4",
        "surface-bright": "#f8f9ff",
        "on-background": "#121c28",
        "inverse-surface": "#27313e",
        "tertiary-fixed": "#e0e3df",
        "surface-container-highest": "#d9e3f4",
        "on-secondary-fixed": "#0e2001",
        "primary": "#154212",
        "on-error": "#ffffff",
        "primary-container": "#2d5a27",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#556b40",
        "surface-container-low": "#eef4ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b5cf9b",
        "tertiary-container": "#4d514e",
        "on-primary-fixed-variant": "#23501e",
        "on-primary-container": "#9dd090",
        "secondary-fixed": "#d1ebb5",
        "surface-container-high": "#dfe9fa",
        "outline": "#72796e",
        "secondary": "#4f653a",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a1d494",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#121c28",
        "on-surface-variant": "#42493e",
        "tertiary-fixed-dim": "#c4c7c3",
        agri: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        earth: {
          100: '#fef3c7',
          500: '#d97706',
          700: '#b45309',
          900: '#78350f',
        }
      },
      spacing: {
        "margin": "32px",
        "gutter": "24px",
        "xs": "4px",
        "base": "8px",
        "sm": "8px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "md": "16px"
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
